baseURL = "https://bcneng.org/"
languageCode = "en-us"
title = "BCN Engineering"
description = "By engineers, for engineers."
theme = "chunky-poster"
paginate = 2
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-161944690-1"
DisqusShortname = ""

[menu]
  [[menu.main]]
    identifier = "netiquette"
    name = "Netiquette"
    url = "/netiquette/"
    weight = 20
  [[menu.main]]
    identifier = "coc"
    name = "Code of Conduct"
    url = "/coc/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "freelancers"
    name = "Freelancers"
    url = "/freelancers/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "BcnEng"
  description = "Slack Community"
  homepageImage = "/images/bcneng_outline.svg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["custom.css"]
  customJS = []

  [params.social]
    rss = true
    twitter = "https://twitter.com/bcn_eng"
    linkedin = "https://www.linkedin.com/company/bcneng/"
    github = "https://github.com/bcneng"
    email = "contact@bcneng.org"

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = false

  [services.twitter]
    disableInlineCSS = true
